// port-lint: source src/build_metadata.rs
package io.github.kotlinmania.awstypes

// Metadata type used by all service SDKs to provide information about the environment the SDK was
// compiled for.

/**
 * The version of Kotlin that was used to compile the SDK.
 *
 * Mirrors upstream `RUST_VERSION`, which is generated by `build.rs` from the `rustc_version`
 * crate. The Kotlin port records the Kotlin compiler version that built this artifact instead.
 */
public const val KOTLIN_VERSION: String = "2.3.21"

/** The version number of the `aws-types-kotlin` artifact compiled into the SDK. */
public const val CORE_PKG_VERSION: String = "0.1.0"

/** Metadata about the environment the SDK was compiled for. */
public data class BuildMetadata(
    /** Which version of Kotlin was used to compile the SDK. */
    public val kotlinVersion: String,
    /** The version number of the `aws-types-kotlin` artifact compiled with the SDK. */
    public val corePkgVersion: String,
    /** The OS the SDK was compiled for. */
    public val osFamily: OsFamily,
)

/** Operating system family that the SDK can be compiled for. */
public enum class OsFamily {
    /** Microsoft Windows. */
    Windows,

    /** Linux. */
    Linux,

    /** Apple macOS. */
    Macos,

    /** Google Android. */
    Android,

    /** Apple iOS. */
    Ios,

    /** A different family of operating system. */
    Other,
    ;

    public companion object {
        /**
         * Returns the OS family this artifact was compiled for.
         *
         * Mirrors upstream `OsFamily::from_env`, whose body is a `cfg!(target_os = ...)` cascade.
         * The Kotlin port resolves the same decision through an `expect`/`actual` value populated
         * per Kotlin Multiplatform target.
         */
        public fun fromEnv(): OsFamily = currentOsFamily

        /**
         * Parses an OS family from a string of the same shape Rust's `cfg!(target_os = ...)` uses.
         *
         * Mirrors upstream `impl From<&str> for OsFamily`.
         */
        public fun fromString(value: String): OsFamily =
            when (value) {
                "windows" -> Windows
                "macos" -> Macos
                "ios" -> Ios
                "linux" -> Linux
                "android" -> Android
                else -> Other
            }
    }
}

/**
 * The OS family this artifact was compiled for.
 *
 * Each target source set provides the concrete value, mirroring upstream's per-`target_os`
 * `cfg!` arms inside `OsFamily::from_env`.
 */
internal expect val currentOsFamily: OsFamily

/** Constant build metadata for this artifact. */
public val BUILD_METADATA: BuildMetadata =
    BuildMetadata(
        kotlinVersion = KOTLIN_VERSION,
        corePkgVersion = CORE_PKG_VERSION,
        osFamily = OsFamily.fromEnv(),
    )
